#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=8,walltime=03:59:00,mem=64gb
#PBS -M losillam@msu.edu
#PBS -m abe
#PBS -N trimming
#PBS -r n


# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated by your job)
# -t use the array flag to submit multiple jobs

# move the session to the work directory
cd ${PBS_O_WORKDIR}/../00_Raw_Reads

# load the program we want to run
module load Java/1.6.0_31
module load Trimmomatic/0.32


# 1) Trim reads


files=(*R1.fastq.gz)     # make an array (list) of the files that we want the script to work on
R2s=(*R2.fastq.gz)

for file in $(seq 0 $((${#files[@]}-1)))
do

dummy=${files[$file]%.fastq.gz}
mv ${files[$file]} ${dummy}_.fastq.gz

dummy2=${R2s[$file]%.fastq.gz}
mv ${R2s[$file]} ${dummy2}_.fastq.gz

name=${files[$file]%_R*}

java -jar $TRIM/trimmomatic-0.32.jar PE -threads 7 -basein ${dummy}_.fastq.gz -baseout ${PBS_O_WORKDIR}/../ReadsTrimmed/tr_${name}.fastq.gz ILLUMINACLIP:/mnt/research/common-data/Bio/Trimmomatic/adapters/TruSeq3-PE.fa:2:30:10 SLIDINGWINDOW:4:5 LEADING:5 TRAILING:5 MINLEN:25

mv ${dummy}_.fastq.gz ${files[$file]}
mv ${dummy2}_.fastq.gz ${R2s[$file]}

done


# 2) Rename the trimmed files

cd ${PBS_O_WORKDIR}/../ReadsTrimmed

files=(tr*.gz)

for i in $(seq 0 $((${#files[@]}-1)))
do 

dummy=(${files[$i]#*_N_})
dummy2=(${files[$i]%%3676*})
name=${dummy2}N_${dummy}

mv ${files[$i]} ${name}


# 3) Unzip the trimmed files

#KEEP THE c option. If you try to delete the gz file (no c option) the program asks for a manual confirmation.
gzip -dc ${name} > ${name%.gz}

done

rm tr*.gz

# writes out a report that you can refer to on walltime/memory usage etc.
check $PBS_JOBID
qstat -f ${PBS_JOBID}

